# Generated by Django 5.2.8 on 2025-11-28 03:55

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('main', '480pDreams (Main)'), ('reviews', 'Reviews Channel'), ('gameplay', 'Gameplay Channel')], max_length=20)),
                ('url', embed_video.fields.EmbedVideoField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='videos/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
