# Generated by Django 5.2.8 on 2025-11-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Square images work best', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell the network about yourself', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_patron',
            field=models.BooleanField(default=False, help_text='Is this user a paying supporter?'),
        ),
    ]
