# Generated by Django 5.2.8 on 2025-12-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_avatar_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_region',
            field=models.CharField(choices=[('NTSC-U', 'NTSC-U (America)'), ('NTSC-J', 'NTSC-J (Japan)'), ('PAL', 'PAL (Europe)')], default='NTSC-U', help_text='Which artwork/title do you want to see by default?', max_length=10),
        ),
    ]
