# Generated by Django 5.2.8 on 2025-12-02 02:46

import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_preferred_region'),
        ('hardware', '0005_hardware_date_acquired_alter_hardware_image_back_and_more'),
        ('library', '0011_game_date_acquired_game_estimated_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkvideo',
            name='is_member_only',
            field=models.BooleanField(default=False, verbose_name='Member Only Content'),
        ),
        migrations.AddField(
            model_name='networkvideo',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_videos', to='library.platform'),
        ),
        migrations.AddField(
            model_name='networkvideo',
            name='related_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.game'),
        ),
        migrations.AddField(
            model_name='networkvideo',
            name='related_hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.hardware'),
        ),
        migrations.AddField(
            model_name='networkvideo',
            name='video_type',
            field=models.CharField(choices=[('gameplay', 'Full Gameplay'), ('gamereview', 'Game Review'), ('hardwarereview', 'Hardware Review'), ('detail', 'Detailed Look'), ('pickups', 'Collection Update'), ('setup', 'Setup Update'), ('news', 'News'), ('restoration', 'Hardware Restoration'), ('modification', 'Hardware Modification')], default='gameplay', max_length=20),
        ),
        migrations.AlterField(
            model_name='networkvideo',
            name='channel',
            field=models.CharField(choices=[('480pGames', '480pGames (Gameplay)'), ('480pReviews', '480pReviews (Reviews)'), ('480pUnbox', '480pUnbox (Unboxing)'), ('480pDreams', '480pDreams (Main)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='networkvideo',
            name='thumbnail',
            field=models.ImageField(help_text='Upload the YouTube Thumbnail here', upload_to='videos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='networkvideo',
            name='url',
            field=embed_video.fields.EmbedVideoField(help_text='YouTube URL (e.g. https://www.youtube.com/watch?v=...)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
