# Generated by Django 5.2.8 on 2025-12-03 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Grant Active')),
                ('expires_at', models.DateField(blank=True, help_text='Leave empty for Lifetime Access', null=True)),
                ('notes', models.TextField(blank=True, help_text='Why was this given? (Internal only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_grant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
