# Generated by Django 5.2.8 on 2025-11-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
