# Generated by Django 5.2.8 on 2025-11-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_hardware_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
            preserve_default=False,
        ),
    ]
