# Generated by Django 5.2.8 on 2025-11-30 20:43

import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_hardware_description_hardware_slug'),
        ('library', '0009_developer_publisher_remove_game_developer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='image',
        ),
        migrations.AddField(
            model_name='hardware',
            name='condition_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hardware',
            name='image_back',
            field=models.ImageField(blank=True, upload_to='hardware/images/', verbose_name='Back'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='image_bottom',
            field=models.ImageField(blank=True, upload_to='hardware/images/', verbose_name='Bottom'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='image_front',
            field=models.ImageField(blank=True, upload_to='hardware/images/', verbose_name='Front (Main)'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='image_side',
            field=models.ImageField(blank=True, upload_to='hardware/images/', verbose_name='Side/Detail'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='image_top',
            field=models.ImageField(blank=True, upload_to='hardware/images/', verbose_name='Top'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='model_numbers',
            field=models.TextField(blank=True, help_text='Comma separated list of model numbers (e.g. SCPH-1001, SCPH-1002)'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='other_variants',
            field=models.ManyToManyField(blank=True, help_text='Link to other color variations or revisions', to='hardware.hardware'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='own_accessories',
            field=models.BooleanField(default=False, verbose_name='Own Accessories/Inserts'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='own_box',
            field=models.BooleanField(default=False, verbose_name='Own Box'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='own_item',
            field=models.BooleanField(default=False, verbose_name='Own Item/Unit'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='platform',
            field=models.ForeignKey(blank=True, help_text='Is this for a specific console? (e.g. PS2 Controller -> PS2)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware', to='library.platform'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='regions',
            field=models.ManyToManyField(blank=True, to='library.region'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='video_condition',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='YouTube Short URL showing item condition'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='video_review',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='480p Review Video'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hardware',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware', to='hardware.hardwaretype'),
        ),
    ]
