# Generated by Django 5.2.8 on 2025-12-01 23:04

import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_hardwaretype_remove_hardware_image_and_more'),
        ('library', '0011_game_date_acquired_game_estimated_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='date_acquired',
            field=models.DateField(blank=True, help_text='When did you get this? Required for Recent Acquisitions.', null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='image_back',
            field=models.ImageField(blank=True, upload_to='hardware/images/'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='image_bottom',
            field=models.ImageField(blank=True, upload_to='hardware/images/'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='image_front',
            field=models.ImageField(blank=True, upload_to='hardware/images/'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='image_side',
            field=models.ImageField(blank=True, upload_to='hardware/images/'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='image_top',
            field=models.ImageField(blank=True, upload_to='hardware/images/'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='model_numbers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='other_variants',
            field=models.ManyToManyField(blank=True, to='hardware.hardware'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware', to='library.platform'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='video_condition',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='video_review',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
